### ISSUE TITLE
README.md Wrong

### ISSUE THREAD

**Issue by CoreDi** [horchi/linux-p4d#13]
In Readme.md Copy from another File is missing.

`- enable p4d start during RPi boot, run the commands`
`cp contrib/p4d /etc/init.d/`
`chmod 750 /etc/init.d/p4d`
`update-rc.d p4d defaults `

Add:

`cp contrib/runp4d /usr/local/bin/`

runp4d is needed for init.d "p4d" after Boot Startup.

**Comment by horchi** [comment]
Fixed README - initV is not longer mentioned to start/stop p4d.
systemd unit files are recommended
