### ISSUE TITLE
Makefile: Ability to just build the `p4` binary. 

### ISSUE THREAD

**Issue by dominic-miglar** [horchi/linux-p4d#16]
Hey there 👋

First of all, I want to thank you for this great project @horchi !

I am just using the `p4` binary of that project in my [froeling-reader-service](https://github.com/logreposit/froeling-reader-service) and have to build a lot of dependencies (e.g. libwebsockets, and so on and so forth..). It would be very useful if there has been a Makefile-target which just builds that particular binary.

Also, there are systems out which are not using `systemd`. Needed to build a workaround [here](https://github.com/logreposit/froeling-reader-service/blob/develop/docker/Dockerfile#L30) in order to build it in a container where the `systemctl` command is not present. A possible solution would be to do that in another (optional) Makefile target or move it even out of the Makefile.

**Comment by horchi** [comment]
have you tried calling `make p4`, this shouldn't need the libwebsockets an the systemd.
Actually I have only systems which full fill a dependencies whereby I can't test it.
Please let me now if there are other needless dependencies.

**Comment by horchi** [comment]
seems to have settled, I close the issue times
