### ISSUE TITLE
Values not updated (MQTT)

### ISSUE THREAD

**Issue by SaimenSays** [horchi/linux-p4d#22]
First of all, thanks for this great piece of Software!

Yesterday I have updated from a years old version to actual from repo. After some struggeling, to get anything all dependencies solved and updated, I got it compiled and now working again on webinterface.
The I did the setup and entered MQTT server. It seems to work from mqtt side, because I see some topics once in a while at my server. Also in p4d.log only shows rare occurance of mqtt output. Even after a whole day not all values are transmitted once.
Can someone help me, what and where to check what is going wrong?

Update: It seems data is not updated correctly, because also in Charts the graphs are not available.
![grafik](https://user-images.githubusercontent.com/10372066/126878887-f7b3381a-f0b0-4f6d-9bbb-3b68250ef4b5.png)

**Comment by hoppel118** [comment]
Welche Version hat du kompiliert?

Ich hatte neulich das gleiche Problem. @horchi hatte dann was korrigiert und ein neues Paket für den Pi veröffentlicht.

Das war damals folgende Version: 0.7.8

Die läuft auch bei mir immer noch.

Gruß Hoppel

**Comment by SaimenSays** [comment]
@hoppel118: Ich habe einen Pull des Repos gemacht und es selbst kompiliert, da ich die alte Version auch aus den Sources kompiliert hatte. In den letzten Monaten hat sich nichts getan, sollte es der aktuelle Master branch sein.
Ich denke inzwischen, dass es eventuell mit Überbleibsel der vorherigen Installation verklemmt hat.
Wenn es keine Vorschläge gibt, werde ich den PI wohl nochmal komplett neu aufsetzen müssen.

**Comment by hoppel118** [comment]
Ach du hast einen Pi. Dann führe doch einfach das Installationsscript aus. ;)

**Comment by SaimenSays** [comment]
Habe jetzt die SD-Karte komplett neu aufgesetzt, nun mit dem Install-Script. Jetzt läuft es zum Glück wieder, also hatte sich irgenwo etwas verklemmt.
Da ich die Messwerte sowieso per MQTT noch auf einem separaten Server speichere, kann ich auf die Historie in der MySQL DB verzichten.
Notiz am Rande: Leider wurden zwischenzeitlich alle Umlaute aus "Fühler", "Stellgröße", etc. entfernt. Somit musste ich nun vieles manuell in meiner Datenbank umkopieren :-/

Funktioniert das Script auch wiederholt, für ein Update?

**Comment by hoppel118** [comment]
Umlaute in Sensorbezeichnungen sind nicht konform. Ich glaube, wir hatten die Diskussion damals bei der MQTT-Anpassung für FHEM und Openhab…

Jo, einfach das Script ausführen, um das Update durchzuführen.

Gruß

**Comment by SaimenSays** [comment]
Ich hatte anfangs auch überlegt ob Englisch oder Deutsch;) Weiß nicht, ob es die Fröhling überhaupt außerhalb des deutschsprachigen Raum gibt...
