### ISSUE TITLE
Since upgrade, cpu starts spinning after a few hours

### ISSUE THREAD

**Issue by faxm0dem** [horchi/linux-p4d#31]
I had to upgrade as my old pi's sdcard crashed.
Since the upgrade, after a few hours `p4d` starts to eat a lot of cpu along with `journald`.
I'll try to add more info to this issue as it happens again

**Comment by horchi** [comment]
do you still have the error with the latest version?
What messages appear in the log

**Comment by faxm0dem** [comment]
Sorry for the lack of update. I don't have the issue anymore.
It was simply due to a second instance of p4d which wasn't killed properly!
