### ISSUE TITLE
Alle Sensoren (auch inaktive) werden über MQTT gesendet

### ISSUE THREAD

**Issue by Tropaion** [horchi/linux-p4d#34]
Hi!
Ich hab gerade neu aufgesetzt und die neueste Version installiert.
Jetzt sendet p4d aber leider alle Sensoren (aktive und inaktive) and HomeAssistant via MQTT.
Hat sich da ein Bug eingeschlichen oder mache ich was falsch?

**Comment by hoppel118** [comment]
Moin, was war die Lösung?

Danke und Gruß Hoppel

**Comment by Tropaion** [comment]
Bin mir auch nicht ganz sicher, nach ein paar Neustarts + Löschen der Topics mittle MQTT Explorer hat es auf einmal funktioniert.

**Comment by hoppel118** [comment]
Alles klar, danke dir! Bei mir steht demnächst auch das Neuaufsetzen inkl. Hardware-Plattformwechsel und Upgrade auf Bullseye an.

Gruß Hoppel
