### ISSUE TITLE
Gauge widget not anymore adjustable if width = 2

### ISSUE THREAD

**Issue by enr0c** [horchi/linux-p4d#36]
![image](https://user-images.githubusercontent.com/33492932/203056917-0d5bb12a-71f3-4f89-b7c7-b92ab33bd209.png)

Steps to reproduce under version 0.9.40-GIT921cc0b - Browser: Chromium OS: Raspberry 
1. Add visualization
2. Select Gauge
3. Select width =2
4. Save
5. User not anymore able to adjust the widget

**Comment by horchi** [comment]
fixed with version 0.9.50
